baseURL = 'https://your-username.github.io/' # Или ваш домен
languageCode = 'ru-ru'
title = 'Мой стильный сайт'
theme = 'risotto'

[params]
  # Основные параметры темы
  description = "Описание моего сайта"
  # Цветовая палитра (доступные варианты: apprentice, base16-dark, base16-light, dracula, gruvbox-dark, gruvbox-light, material, papercolor-dark, papercolor-light, solarized-dark, solarized-light, tender, tokyo-night-dark, tokyo-night-light, windows-95, windows-95-light)
  palette = "dracula" 

[menu]
  # Настройка меню (если нужно)
  [[menu.main]]
    identifier = "about"
    name = "Обо мне"
    url = "/about/"
    weight = 10